USE [master]
GO

/****** Object:  Database [ISIS]    Script Date: 10/11/2012 15:30:16 ******/
CREATE DATABASE [ISIS] ON  PRIMARY 
( NAME = N'ISIS', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ISIS.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ISIS_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ISIS_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ISIS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ISIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ISIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ISIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ISIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ISIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ISIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [ISIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ISIS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ISIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ISIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ISIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ISIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ISIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ISIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ISIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ISIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ISIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ISIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ISIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ISIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ISIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ISIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ISIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ISIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ISIS] SET  READ_WRITE 
GO

ALTER DATABASE [ISIS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ISIS] SET  MULTI_USER 
GO

ALTER DATABASE [ISIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ISIS] SET DB_CHAINING OFF 
GO

